# Generated by Django 3.0.5 on 2020-04-24 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_personalnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
